##### Basic Request ################################

POST http://localhost:3000/api/v1/flight/search
Content-Type: application/json

{
    "origin": "CGK", 
    "destination": "DPS", 
    "departure_date": "2025-12-15", 
    "return_date": null, 
    "passengers": 1, 
    "cabin_class": "economy"
}

##### Filter by Departure Time #####################

POST http://localhost:3000/api/v1/flight/search
Content-Type: application/json

{
    "origin": "CGK", 
    "destination": "DPS", 
    "departure_date": "2025-12-15", 
    "departure_time": "12:00:00",
    "return_date": null, 
    "passengers": 1, 
    "cabin_class": "economy"
}

##### Filter by Airline ############################

POST http://localhost:3000/api/v1/flight/search
Content-Type: application/json

{
    "origin": "CGK", 
    "destination": "DPS", 
    "departure_date": "2025-12-15", 
    "return_date": null, 
    "passengers": 1, 
    "cabin_class": "economy",
    "airline": "AirAsia"
}

##### Sort by Price ################################

POST http://localhost:3000/api/v1/flight/search
Content-Type: application/json

{
    "origin": "CGK", 
    "destination": "DPS", 
    "departure_date": "2025-12-15", 
    "return_date": null, 
    "passengers": 1, 
    "cabin_class": "economy",
    "sort_by": {
        "price": "asc"
    }
}

##### Sort by Arrival ##############################

POST http://localhost:3000/api/v1/flight/search
Content-Type: application/json

{
    "origin": "CGK", 
    "destination": "DPS", 
    "departure_date": "2025-12-15", 
    "return_date": null, 
    "passengers": 1, 
    "cabin_class": "economy",
    "sort_by": {
        "arrival": "desc"
    }
}
